import type { PracticeVideo } from "./types";

export const demoVideos: PracticeVideo[] = [
  {
    id: "video-001",
    slug: "new-video-workflow",
    title: "New video workflow: done before perfect",
    creator: "SpeakLoop Studio",
    duration: 105,
    level: "intermediate",
    topics: ["Daily vlog", "Creator life", "Mindset"],
    description:
      "A short creator-style monologue for practicing natural pacing, contractions, and everyday transitions.",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
    posterUrl:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    subtitleLines: [
      {
        id: "line-001",
        startTime: 0,
        endTime: 4.2,
        english: "Okay, today I am trying a new workflow for making videos.",
        chinese: "好，今天我想尝试一种新的视频制作流程。",
        wordCardIds: ["card-001"],
      },
      {
        id: "line-002",
        startTime: 4.2,
        endTime: 8.6,
        english: "The goal is simple: finish first, polish later.",
        chinese: "目标很简单：先完成，再打磨。",
        wordCardIds: ["card-002"],
      },
      {
        id: "line-003",
        startTime: 8.6,
        endTime: 13.2,
        english: "If I wait until everything feels perfect, I never post anything.",
        chinese: "如果我总等到一切都完美，我就永远发不出去。",
        wordCardIds: ["card-003"],
      },
      {
        id: "line-004",
        startTime: 13.2,
        endTime: 18.4,
        english: "So I write a tiny outline, record one take, and keep moving.",
        chinese: "所以我只写一个小提纲，录一遍，然后继续推进。",
        wordCardIds: ["card-004"],
      },
      {
        id: "line-005",
        startTime: 18.4,
        endTime: 23.7,
        english: "It is not about being careless. It is about building momentum.",
        chinese: "这不是草率，而是在建立行动的势头。",
        wordCardIds: ["card-005"],
      },
      {
        id: "line-006",
        startTime: 23.7,
        endTime: 29.4,
        english: "When the first version exists, improving it becomes much easier.",
        chinese: "当第一版已经存在时，改进它就容易多了。",
        wordCardIds: ["card-006"],
      },
      {
        id: "line-007",
        startTime: 29.4,
        endTime: 35,
        english: "I can hear what sounds awkward and cut what does not help.",
        chinese: "我能听出哪里别扭，也能删掉没有帮助的部分。",
        wordCardIds: ["card-007"],
      },
      {
        id: "line-008",
        startTime: 35,
        endTime: 41.2,
        english: "This little rule has made practice feel lighter and more consistent.",
        chinese: "这个小规则让练习变得更轻松，也更容易坚持。",
        wordCardIds: ["card-008"],
      },
      {
        id: "line-009",
        startTime: 41.2,
        endTime: 47.6,
        english: "If you are practicing English, try the same thing with one sentence.",
        chinese: "如果你在练英语，也可以从一句话开始这样做。",
        wordCardIds: ["card-009"],
      },
      {
        id: "line-010",
        startTime: 47.6,
        endTime: 54.5,
        english: "Listen once, copy the rhythm, record yourself, and compare.",
        chinese: "先听一遍，模仿节奏，录下自己，再做对比。",
        wordCardIds: ["card-010"],
      },
    ],
    wordCards: [
      {
        id: "card-001",
        term: "workflow",
        meaning: "工作流程；做一件事的固定步骤",
        example: "I am trying a new workflow for making videos.",
        status: "new",
      },
      {
        id: "card-002",
        term: "polish",
        meaning: "打磨；润色；让内容更精致",
        example: "Finish first, polish later.",
        status: "learning",
      },
      {
        id: "card-003",
        term: "post",
        meaning: "发布内容",
        example: "I never post anything.",
        status: "known",
      },
      {
        id: "card-004",
        term: "one take",
        meaning: "一次录制完成的一遍",
        example: "Record one take, and keep moving.",
        status: "new",
      },
      {
        id: "card-005",
        term: "momentum",
        meaning: "势头；推动你继续做下去的动力",
        example: "It is about building momentum.",
        status: "learning",
      },
      {
        id: "card-006",
        term: "first version",
        meaning: "第一版；初稿",
        example: "When the first version exists, improving it becomes easier.",
        status: "new",
      },
      {
        id: "card-007",
        term: "awkward",
        meaning: "别扭的；不自然的",
        example: "I can hear what sounds awkward.",
        status: "learning",
      },
      {
        id: "card-008",
        term: "consistent",
        meaning: "持续稳定的",
        example: "Practice feels lighter and more consistent.",
        status: "new",
      },
      {
        id: "card-009",
        term: "try the same thing",
        meaning: "用同样的方法试一试",
        example: "Try the same thing with one sentence.",
        status: "new",
      },
      {
        id: "card-010",
        term: "compare",
        meaning: "对比；比较",
        example: "Record yourself, and compare.",
        status: "known",
      },
    ],
  },
];

export function getVideoBySlug(slug: string) {
  return demoVideos.find((video) => video.slug === slug) ?? demoVideos[0];
}
